lista =[
    "Examen_Microscopico_Epitelial",
    "Examen_Microscopico_Leucocitos",
    "Examen_Microscopico_Hematies",
    "Examen_Microscopico_Cilindros",
    "Examen_Microscopico_Mucus",
    "Examen_Microscopico_Cristales",
    "Examen_Microscopico_Germenes",
    "Examen_Fisico_Reaccion",
    "Examen_Fisico_Aspecto",
    "Bilirrubina_Total",
    "Bilirrubina_Directa",
    "Bilirrubina_Indirecta",
    "Fosfatasa_Alcalina_Recien_Nacido",
    "Fosfatasa_Alcalina_Bebe",
    "Fosfatasa_Alcalina_Ninio",
    "Fosfatasa_Alcalina_Adulto",
    "Glutamico_Piruvica_Hombre",
    "Glutamico_Piruvica_Mujer",
    "Glutamico_Oxalacetica_Hombre",
    "Glutamico_Oxalacetica_Mujer",
    "Trigliceridos",
    "Colesterol_Total",
    "Hdl_Hombre",
    "Hdl_Mujer",
    "Ldl",
    "Creatinina",
    "Urea",
    "Glucosa",
    "Globulos_Rojos_Total_Mujer",
    "Globulos_Rojos_Total_Hombre",
    "Hematocritos_Hombre",
    "Hematocritos_Mujer",
    "Hemoglobina_G_Hombre",
    "Hemoglobina_G_Mujer",
    "Serie_Roja_Aspecto",
    "Leucocitos",
    "Neutrofilos_Cayado",
    "Neutrofilos_Segmentado",
    "Eosinofilos",
    "Basofilos",
    "Linfocitos",
    "Monocitos"
]
lista1 =[
    "ExamenMicroscopicoEpitelial",
    "ExamenMicroscopicoLeucocitos",
    "ExamenMicroscopicoHematies",
    "ExamenMicroscopicoCilindros",
    "ExamenMicroscopicoMucus",
    "ExamenMicroscopicoCristales",
    "ExamenMicroscopicoGermenes",
    "ExamenFisicoReaccion",
    "ExamenFisicoAspecto",
    "BilirrubinaTotal",
    "BilirrubinaDirecta",
    "BilirrubinaIndirecta",
    "FosfatasaAlcalinaRecienNacido",
    "FosfatasaAlcalinaBebe",
    "FosfatasaAlcalinaNinio",
    "FosfatasaAlcalinaAdulto",
    "GlutamicoPiruvicaHombre",
    "GlutamicoPiruvicaMujer",
    "GlutamicoOxalaceticaHombre",
    "GlutamicoOxalaceticaMujer",
    "Trigliceridos",
    "ColesterolTotal",
    "HdlHombre",
    "HdlMujer",
    "Ldl",
    "Creatinina",
    "Urea",
    "Glucosa",
    "GlobulosRojosTotalMujer",
    "GlobulosRojosTotalHombre",
    "HematocritosHombre",
    "HematocritosMujer",
    "HemoglobinaGHombre",
    "HemoglobinaGMujer",
    "SerieRojaAspecto",
    "Leucocitos",
    "NeutrofilosCayado",
    "NeutrofilosSegmentado",
    "Eosinofilos",
    "Basofilos",
    "Linfocitos",
    "Monocitos"
]

a = open('rutas.txt', "w")
for c in range(len(lista)):
    j = lista[c]
    i = lista1[c]
    b = j.lower()
    a.write(f'api.add_resource({i}Api, /Clidas/api/rutinas/{b}')
    a.write('\n')
    a.write(f'api.add_resource({i}Api, /Clidas/api/rutinas/{b}/<id>')
    a.write('\n')
a.close()
