lista =[
    "ExamenMicroscopicoEpitelial",
    "ExamenMicroscopicoLeucocitos",
    "ExamenMicroscopicoHematies",
    "ExamenMicroscopicoCilindros",
    "ExamenMicroscopicoMucus",
    "ExamenMicroscopicoCristales",
    "ExamenMicroscopicoGermenes",
    "ExamenFisicoReaccion",
    "ExamenFisicoAspecto",
    "BilirrubinaTotal",
    "BilirrubinaDirecta",
    "BilirrubinaIndirecta",
    "FosfatasaAlcalinaRecienNacido",
    "FosfatasaAlcalinaBebe",
    "FosfatasaAlcalinaNinio",
    "FosfatasaAlcalinaAdulto",
    "GlutamicoPiruvicaHombre",
    "GlutamicoPiruvicaMujer",
    "GlutamicoOxalaceticaHombre",
    "GlutamicoOxalaceticaMujer",
    "Trigliceridos",
    "ColesterolTotal",
    "HdlHombre",
    "HdlMujer",
    "Ldl",
    "Creatinina",
    "Urea",
    "Glucosa",
    "GlobulosRojosTotalMujer",
    "GlobulosRojosTotalHombre",
    "HematocritosHombre",
    "HematocritosMujer",
    "HemoglobinaGHombre",
    "HemoglobinaGMujer",
    "SerieRojaAspecto",
    "Leucocitos",
    "NeutrofilosCayado",
    "NeutrofilosSegmentado",
    "Eosinofilos",
    "Basofilos",
    "Linfocitos",
    "Monocitos"
]

for i in lista:
    a = open(f'{i}.txt', "w")
    a.close()